@startuml
skinparam monochrome true
skinparam shadowing false
skinparam defaultFontName "Barlow Semi Condensed"
skinparam defaultFontSize 14

title WebApp Flow

start
:Central.init
assign EXE_PATH, APP_PATH, VIEW_PATH
setup caches, config, bootstraps
assign modules, modules.init();
:import.mjs
routes.mjs;
:Central.reloadModuleInit();
:create app (fastify / express)
setup app - static file, cookies, handle not found;
:RouteList.createRoute()
- routeAdapter.addRoute()
  - app.get / app.post / app.put / app.delete;
:app.listen();
end

start
:request<
:app handle request;
if(route exist) then (no)
:redirect to /pages/404;
end
else(yes)

:RouteList
parse request.params.action
parse request.params.controller;
:HelperRoute.execute();
:Controller.execute();
:Controller.action_xxx();
if(controller error) then (yes)
:HelperRoute.execute(ErrorFactory);
:Response>
end
else(no)
:Response>
end

@enduml
